# Generated by Django 2.2.3 on 2019-07-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_sakit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='jadwal_praktek',
            field=models.DateField(),
        ),
    ]
